development: &default
  adapter: 'postgresql'
  host: <%= ENV['DBHOST'] || 'localhost' %>
  port: 5432
  encoding: utf8
  database: <%= ENV['DBNAME'] || 'modules_development' %>
  pool: 20
  username: modules
  password: modulesbase
  schema_search_path: public

staging:
  <<: *default